<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_API Testing.xlsx</name>
   <tag></tag>
   <elementGuidId>0dc481ff-9cdc-4ebc-88b7-38ae989bc239</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uploadedfilename</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='uploadedfilename']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>290dff60-fabf-4069-8d7b-234b79af69f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadedfilename</value>
      <webElementGuid>e5d57d69-257d-4ac4-93fe-62eeec9e679d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>API Testing.xlsx</value>
      <webElementGuid>b2ba8305-953e-4c46-a800-813ad32ae45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadedfilename&quot;)</value>
      <webElementGuid>e9e63258-7b0a-42a8-a0bb-a805d1499c1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='uploadedfilename']</value>
      <webElementGuid>bf16c9e7-82b3-4c34-a255-9e8906403444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You uploaded this file:'])[1]/following::p[1]</value>
      <webElementGuid>fa2da5a2-bb2f-4e7e-a04e-aa1d203d4849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uploaded File'])[1]/following::p[2]</value>
      <webElementGuid>33a6cd3d-024d-4840-96bb-6a4411a384c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Another'])[1]/preceding::p[1]</value>
      <webElementGuid>aab736e8-16b6-4f07-9c9d-54586f957f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EvilTester.com'])[1]/preceding::p[1]</value>
      <webElementGuid>436f8f7f-519d-4a52-b044-cb2ced668767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='API Testing.xlsx']/parent::*</value>
      <webElementGuid>31e8d87b-3c8b-4de3-af72-56e37552e0b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/p</value>
      <webElementGuid>2bd4326c-3c52-4d87-b0f4-3a7a7498b365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'uploadedfilename' and (text() = 'API Testing.xlsx' or . = 'API Testing.xlsx')]</value>
      <webElementGuid>d820b153-ec1e-482f-a5fe-e7265cc660c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
