<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SQL Intro</name>
   <tag></tag>
   <elementGuidId>b99a58ca-26a2-4d15-992f-b8de2c33ca52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leftmenuinnerinner > a:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftmenuinnerinner']/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e7c14d5a-c827-4ba5-9d86-2cd7cbf8a413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>d0829a27-6172-4bd2-b9f8-26e5c44e51c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>sql_intro.asp</value>
      <webElementGuid>2d00fa49-02f0-411d-9281-fc0b41fb5959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SQL Intro</value>
      <webElementGuid>51cde773-c848-41bf-94ff-7e485eff2b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftmenuinnerinner&quot;)/a[2]</value>
      <webElementGuid>73c000b9-85b0-48b2-b730-ef24d377cef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftmenuinnerinner']/a[2]</value>
      <webElementGuid>88181f72-8bef-47aa-9153-4424ed3a9d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SQL Intro')]</value>
      <webElementGuid>a9a06100-3300-42ab-b071-bf843beb59fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQL HOME'])[1]/following::a[1]</value>
      <webElementGuid>35886f13-8d18-495b-b911-c14d91ba3766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQL'])[4]/following::a[2]</value>
      <webElementGuid>e8b1999c-d91b-4e25-a282-653442d5e438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQL Syntax'])[1]/preceding::a[1]</value>
      <webElementGuid>20245d06-4559-4e33-a333-1854830448b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQL Select'])[1]/preceding::a[2]</value>
      <webElementGuid>5a88c0bc-f902-4d48-9711-e05d442f70de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SQL Intro']/parent::*</value>
      <webElementGuid>43298783-2a60-4850-a014-eccfa6b5e916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'sql_intro.asp')]</value>
      <webElementGuid>451b5aec-cae6-4bd7-8a0d-dc8b7ef924e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a[2]</value>
      <webElementGuid>039072a0-bd67-44b8-ae8d-44151ab2a437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'sql_intro.asp' and (text() = 'SQL Intro' or . = 'SQL Intro')]</value>
      <webElementGuid>75f05fb0-bfe6-4526-9a89-cad68b88b234</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
