<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_to continue to Gmail_identifier</name>
   <tag></tag>
   <elementGuidId>136b3b3d-72b5-4d1d-b32c-cdf13b7870aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#identifierId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='identifierId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21124393-fabe-409f-ae3d-b3553ce70650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>fabfc8dd-5661-4514-aeff-6da90cf84892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>whsOnd zHQkBf</value>
      <webElementGuid>64387aae-639a-4686-9d5c-66c280516824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>YPqjbf</value>
      <webElementGuid>33741e72-6f84-48c6-bc6f-7f3e80abfc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>c5129907-9489-44c2-9996-e560a5c38fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d315d30d-9905-429a-b3e7-341bf94f81e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>46bdea31-f9ae-471c-8bb1-5816e668d28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email or phone</value>
      <webElementGuid>5274c441-6eee-409b-9a3f-487b0a3f5222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identifier</value>
      <webElementGuid>746aaca5-0126-4d5f-8a59-c48bf41a830c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>4aa3e5c4-bcf0-40c1-88d4-cf368d620a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identifierId</value>
      <webElementGuid>f10bbc02-fed1-4f26-96fc-93a0b67f7deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>3a48d35e-24fa-4c2a-bb06-b3d0fa640ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-initial-dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>c61cc156-0f0d-4551-9d6d-e61965bafec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-initial-value</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>03548c29-6f26-4417-8429-fd59139cecae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>badinput</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f995d2b1-1352-485f-9000-22df67f9fa3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identifierId&quot;)</value>
      <webElementGuid>5331fca4-1851-40cd-bcf2-4ad513292e40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='identifierId']</value>
      <webElementGuid>3319cc95-8ded-47e3-8b16-0831df8e1898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yDmH0d']/c-wiz/div/div[2]/div/div/div/form/span/section/div/div/div/div/div/div/div/input</value>
      <webElementGuid>c7eb4d61-74ff-4c1f-bf81-1ec555031515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>cb5ab4fb-b617-448c-98a8-7e046d4b9de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'identifier' and @id = 'identifierId']</value>
      <webElementGuid>6f27cd61-a2f1-4c8b-a9a5-80fae054b5d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
