<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Google</name>
   <tag></tag>
   <elementGuidId>2927ed53-d0a9-4f4b-b9b7-982d038cd9c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ol > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hcfe-content']/section/div/div/article/section/div/div/div/div[4]/ol/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cb18e820-3eae-4eba-b5fd-0e5b7c8069b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/</value>
      <webElementGuid>f386af5c-9584-4723-8471-f4d9de8bee0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>5ed4f375-84be-4b16-9271-7c60d5395424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>75e507ef-f358-452a-baa1-300a4f4ab339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Google</value>
      <webElementGuid>0ed635c8-b0af-4ce4-bb5f-07d0cefff24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hcfe-content&quot;)/section[@class=&quot;primary-container&quot;]/div[@class=&quot;page-width-container&quot;]/div[@class=&quot;main-content&quot;]/article[@class=&quot;article page no-article-survey&quot;]/section[@class=&quot;article-container&quot;]/div[@class=&quot;inline-feedback__container&quot;]/div[@class=&quot;article-content-container&quot;]/div[@class=&quot;cc&quot;]/div[4]/ol[1]/li[1]/a[1]</value>
      <webElementGuid>293d45a0-08bf-403b-8017-3b1b0d466ce3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hcfe-content']/section/div/div/article/section/div/div/div/div[4]/ol/li/a</value>
      <webElementGuid>a5ceda74-e98f-441f-b084-d2e12cdb485d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Google')])[2]</value>
      <webElementGuid>68a69224-0208-45f7-ad7e-b69163270933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Important:'])[2]/following::a[1]</value>
      <webElementGuid>0daac073-eb21-461b-b2b1-16991d03d66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click the result that you want.'])[1]/preceding::a[1]</value>
      <webElementGuid>0ebddc15-e07b-452a-9b31-7111d3bec235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Google']/parent::*</value>
      <webElementGuid>83eb67eb-8aa6-4e41-a364-9d50d257d73c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com/')]</value>
      <webElementGuid>b85d6fb7-90bf-4b2d-9686-e6e7559950aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/a</value>
      <webElementGuid>986b67fb-53d7-482c-b05d-ca10a03575c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com/' and (text() = 'Google' or . = 'Google')]</value>
      <webElementGuid>a3f771d4-07fe-4e1c-91bf-f62e2fcbeb32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
