<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_JAVA</name>
   <tag></tag>
   <elementGuidId>5d94cfda-241a-4a7d-9b68-b16c21bc0aa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topnav']/div/div/a[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f279921e-32ab-4a62-b52f-2b091686b66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-bar-item w3-button ga-nav</value>
      <webElementGuid>28bfed33-58bd-447e-a34c-09ec15918026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/java/default.asp</value>
      <webElementGuid>8a13ff87-d5d3-42ef-8825-a13a979f1af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Java Tutorial</value>
      <webElementGuid>42d13614-d454-4eaa-8195-4b4a7bbb0da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JAVA</value>
      <webElementGuid>16f84a2e-13c7-445d-b48d-bb05f00022cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topnav&quot;)/div[1]/div[@class=&quot;w3-bar w3-left topnavbar&quot;]/a[@class=&quot;w3-bar-item w3-button ga-nav&quot;]</value>
      <webElementGuid>49f35c55-ab7f-42ed-832d-ff25721b2fb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topnav']/div/div/a[8]</value>
      <webElementGuid>7631f41d-af74-4e12-acde-da5cfa044b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'JAVA')])[2]</value>
      <webElementGuid>e9af018c-e16e-4abc-b964-c55caf5b704e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PYTHON'])[1]/following::a[1]</value>
      <webElementGuid>5487bbbf-31b1-45c8-ab50-37b551ef6903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQL'])[3]/following::a[2]</value>
      <webElementGuid>afc29408-0d98-41e9-b1ff-1fd9d60c58a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PHP'])[3]/preceding::a[1]</value>
      <webElementGuid>223a8479-28a7-4c2d-ae67-3a5aa48f7093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOOTSTRAP'])[1]/preceding::a[2]</value>
      <webElementGuid>72c2574b-6cda-4560-a263-d4fe6e760469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JAVA']/parent::*</value>
      <webElementGuid>1912fd27-6f7f-414e-82a0-cd8656b37c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/java/default.asp')])[3]</value>
      <webElementGuid>6d755b29-bc99-4747-ba28-0bc3bee4cb9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a[8]</value>
      <webElementGuid>cadd3b1d-9fb4-422f-a2ab-7a38a8970028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/java/default.asp' and @title = 'Java Tutorial' and (text() = 'JAVA' or . = 'JAVA')]</value>
      <webElementGuid>991b1037-dbd5-487c-aa75-5cb376a5153c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
