<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Next</name>
   <tag></tag>
   <elementGuidId>848b96c8-4d2e-4879-b8d0-09be8189287f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._1M6AF._3QJHf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[3]/div/div/div[3]/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a81740c4-03a5-457a-8505-3bb21b93aaf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4715900b-0cac-4bbc-8a3c-0f46d99db090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bed5599e-756d-4f7e-a9f8-9a0fd9f1c472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>link-device-phone-number-entry-next-button</value>
      <webElementGuid>d89056de-3f8c-4390-88e5-6d45efecb137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1M6AF _3QJHf</value>
      <webElementGuid>3ba2808f-fbfb-4350-9b14-e0a571b1a66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>e5b310d8-910a-4458-a3d5-1cb332550b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;_1Fm4m tsBgS app-wrapper-web font-fix os-win&quot;]/div[@class=&quot;landing-wrapper&quot;]/div[@class=&quot;landing-window&quot;]/div[@class=&quot;landing-main&quot;]/div[@class=&quot;tvf2evcx m0h2a7mj lb5m6g5c j7l1k36l ktfrpxia nu7pwgvd p357zi0d dnb887gk gjuq5ydh i2cterl7 fhf7t426 f8m0rgwh gndfcl4n light&quot;]/div[@class=&quot;tvf2evcx m0h2a7mj lb5m6g5c j7l1k36l ktfrpxia nu7pwgvd p357zi0d dnb887gk gjuq5ydh i2cterl7 fhf7t426 f8m0rgwh elxb2u3l&quot;]/div[@class=&quot;tvf2evcx m0h2a7mj lb5m6g5c j7l1k36l ktfrpxia nu7pwgvd dnb887gk o2es7gts i2cterl7 iyjcf3gk&quot;]/div[@class=&quot;_1M6AF _3QJHf&quot;]</value>
      <webElementGuid>1b9dc073-8284-420b-917f-8c6b09a6c341</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[3]/div/div/div[3]/div[3]/div</value>
      <webElementGuid>baa56a94-6cbb-4b9b-9e04-d184c49a2cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[1]/following::div[7]</value>
      <webElementGuid>98fe869a-2ae3-4707-af2e-55cb12f3e9b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a country and enter your WhatsApp phone number.'])[1]/following::div[11]</value>
      <webElementGuid>a551b030-e8bd-4275-941c-d60e41c2c67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link with QR code'])[1]/preceding::div[3]</value>
      <webElementGuid>2ef302ed-cd8e-42b0-bd57-e54740f99544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div</value>
      <webElementGuid>6569af5e-a7c0-42d8-8e6b-230f106a13e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>b1f04642-fa0d-4d3f-a3e9-7e25e3c6b7cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
