<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>d5dd4db0-d81e-49a8-a0ea-80008bf7536b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[4]/header/div[2]/div/span/div[4]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f080e124-64f6-4976-a3f4-b73d481918e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>3ff3cb5e-e1d2-4d80-ab2b-bc8a446afde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>7946f0e9-fa6b-4f8f-bb75-ae7e12974721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;_1Fm4m _1h2dM app-wrapper-web font-fix os-win&quot;]/div[@class=&quot;two _1jJ70&quot;]/div[@class=&quot;_2Ts6i _3RGKj&quot;]/header[@class=&quot;g0rxnol2 ercejckq cm280p3y p357zi0d gndfcl4n kcgo1i74 ln8gz9je e8h85j61 emrlamx0 aiput80m lyvj5e2u l9g3jx6n f6ipylw5&quot;]/div[@class=&quot;_604FD&quot;]/div[@class=&quot;_1sPvB _2XdMx&quot;]/span[1]/div[@class=&quot;_3OtEr&quot;]/div[@class=&quot;_3ndVb fbgy3m38 ft2m32mm oq31bsqd nu34rnf1&quot;]/span[1]</value>
      <webElementGuid>bb1c3caf-e0f8-4765-b054-5302c187d96e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[4]/header/div[2]/div/span/div[4]/div/span</value>
      <webElementGuid>982e8720-5d72-40a3-b059-df84c6276cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search or start new chat'])[1]/preceding::span[5]</value>
      <webElementGuid>924741bd-8d85-428a-86da-5be18da9eb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update available'])[1]/preceding::span[7]</value>
      <webElementGuid>07d1c14b-5af9-47ab-a0db-99e30f403c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div[4]/div/span</value>
      <webElementGuid>55d35e69-b220-44a7-999d-2b769c702c5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
