<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Link with phone number</name>
   <tag></tag>
   <elementGuidId>15c2c35a-3af5-4b1c-a6b6-3c2a7fc21aad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span._3iLTh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[3]/div/div/div/div[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>66c031fc-6fbb-4cf0-882c-6562ef8d8780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3989d064-aedd-473c-b1bc-f40badb34b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5b3389af-57a9-4abf-852c-6444a4d80cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>link-device-qrcode-alt-linking-hint</value>
      <webElementGuid>41ddca2e-bd61-4f81-8acd-e45ec87b4bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_3iLTh</value>
      <webElementGuid>371bd932-2506-4308-880e-41e02dedcebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link with phone number</value>
      <webElementGuid>85aac534-a3e0-4ff9-8f1b-979a62a94079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;_1Fm4m tsBgS app-wrapper-web font-fix os-win&quot;]/div[@class=&quot;landing-wrapper&quot;]/div[@class=&quot;landing-window&quot;]/div[@class=&quot;landing-main&quot;]/div[@class=&quot;vGm4z _2Jgm7&quot;]/div[@class=&quot;_1x9Rv _3qC8O&quot;]/div[@class=&quot;_3rDmx&quot;]/div[@class=&quot;_2rQUO&quot;]/span[@class=&quot;_3iLTh&quot;]</value>
      <webElementGuid>3c3683ea-20b0-4283-8455-cc678049f94d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[3]/div/div/div/div[3]/div/span</value>
      <webElementGuid>86c11de7-11b0-4d0e-ad0f-4826d2866e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Point your phone to this screen to capture the QR code'])[1]/following::span[3]</value>
      <webElementGuid>f9140c58-1961-4283-a770-49fe8af40622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link a device'])[1]/following::span[4]</value>
      <webElementGuid>06b81327-4ef0-4eb3-bb3c-828516187665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutorial'])[1]/preceding::span[1]</value>
      <webElementGuid>ff0fc178-b469-43bb-8e61-ce21b7aecd89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need help to get started?'])[1]/preceding::span[1]</value>
      <webElementGuid>794546f3-085a-44dd-a9d2-f476dbf0842c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Link with phone number']/parent::*</value>
      <webElementGuid>a1f5e845-5134-45bf-80a3-798a9c044ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/span</value>
      <webElementGuid>dd8b6cd2-3e38-4100-a04c-33bd01141238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Link with phone number' or . = 'Link with phone number')]</value>
      <webElementGuid>a04c1ed7-836e-43ff-822d-78cca5d2d65b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
