<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload a File_filename</name>
   <tag></tag>
   <elementGuidId>62838064-936a-4cd8-b21a-2ca86763f9ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fileinput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fileinput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c4acfce-9457-44cc-bf15-5f05d1cd6793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>6b0f90b8-7655-4d77-9226-2931de3602e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fileinput</value>
      <webElementGuid>e8083bf0-687b-4c49-91df-a35f321be96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filename</value>
      <webElementGuid>bf63e468-91a8-4565-ba23-3c42f37c5767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fileinput&quot;)</value>
      <webElementGuid>4e225855-3917-453c-bd5f-6d72cc7f3ef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fileinput']</value>
      <webElementGuid>276b0f9b-aa1c-4184-9ff9-5a72183df059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1089c9f4-1b4f-42e4-9df8-f474441438c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'fileinput' and @name = 'filename']</value>
      <webElementGuid>928ec227-2ce9-4d79-bd9b-4b0e9ef4ffd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
