<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>651c27fa-b1ce-4261-a7be-5aa87b1d99a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#guide-icon > yt-icon-shape.style-scope.yt-icon > icon-shape.yt-spec-icon-shape > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//yt-icon[@id='guide-icon']/yt-icon-shape/icon-shape/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>68848b5c-2867-4424-ad49-27f7c35b3aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start&quot;)/yt-icon-button[@id=&quot;guide-button&quot;]/button[@id=&quot;button&quot;]/yt-icon[@id=&quot;guide-icon&quot;]/yt-icon-shape[@class=&quot;style-scope yt-icon&quot;]/icon-shape[@class=&quot;yt-spec-icon-shape&quot;]/div[1]</value>
      <webElementGuid>5f413b7f-1784-41d9-a797-8c2f0e725fd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//yt-icon[@id='guide-icon']/yt-icon-shape/icon-shape/div</value>
      <webElementGuid>afc0f55e-c246-45f3-89a1-0b289235f2d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::div[1]</value>
      <webElementGuid>2dece0f2-1ac6-44aa-afea-d39f66cf08be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NaN / NaN'])[1]/following::div[29]</value>
      <webElementGuid>b654fc5c-52d1-4fe5-b4ae-2d14c7d879e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IN'])[1]/preceding::div[6]</value>
      <webElementGuid>e23f163a-23c8-47e9-8d90-0776340f64b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip navigation'])[1]/preceding::div[6]</value>
      <webElementGuid>dc87dfe8-447e-41da-90e4-e693a34a1b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//yt-icon-button[2]/button/yt-icon/yt-icon-shape/icon-shape/div</value>
      <webElementGuid>7db48a4b-6cc9-4d98-992a-52e7d346b75b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
