<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SoccerFootballBaseballBasketballsnookerRugbyGolfNetball_sports</name>
   <tag></tag>
   <elementGuidId>fd7b0f19-729c-4976-90ee-1a3dad27576e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='sports'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9daf0383-ed68-4b7e-9140-e7e0f13b51cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6b514467-2aa0-438c-bc60-7c458de5d9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>1f747562-7d06-4c7f-98bd-05e1791d3b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sports</value>
      <webElementGuid>d2ffcb61-23b5-4380-aa19-e9a0bdfa69ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>basketball</value>
      <webElementGuid>24c6438c-59dd-4884-b439-5967ca520981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;indent-main&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;column-center&quot;]/form[1]/input[4]</value>
      <webElementGuid>d22d52b9-3112-40ce-bbef-93ef2a10a9c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='sports'])[4]</value>
      <webElementGuid>cc7f1075-430b-4bdd-af38-e340710f8049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div[2]/form/input[4]</value>
      <webElementGuid>56576889-5558-4862-9be1-e75d78df47f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>0a4f84a5-fc89-47ae-b12a-277b81265b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @checked = 'yes' and @name = 'sports']</value>
      <webElementGuid>46ebb96d-b21c-45cb-91e0-c684fa85b4d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
