<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign up now_password</name>
   <tag></tag>
   <elementGuidId>ce122d76-70bb-452b-a27e-a1d89a7c39c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>380d2504-bb13-4028-909c-de7fbc38c1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>92f447f4-5393-4735-8dc6-f192e8de063f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>class-color-placeholder</value>
      <webElementGuid>f3b99c7e-a83e-4c4f-9e2a-51e0a9042cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password2</value>
      <webElementGuid>2ec6244f-7bed-47b2-bd9f-6723df8f79e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>ad84e5cf-ab89-4e6b-acd8-1afe21f2ba61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>35e03ef7-db3a-4e42-98ce-a2f929765abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password2&quot;)</value>
      <webElementGuid>f3b7dc33-55ea-4382-bafd-5c1c1bc9f268</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password2']</value>
      <webElementGuid>e114acf0-9fca-423a-912b-2627341745f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/input[2]</value>
      <webElementGuid>3b15ff86-fd6e-45b2-b8c9-e29cf49d93e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>8229579b-08ca-407c-a41f-a23860f61f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'password2' and @placeholder = 'Password' and @name = 'password']</value>
      <webElementGuid>68761aa9-762d-4546-8641-c5d73423ac6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
