<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PYTHON</name>
   <tag></tag>
   <elementGuidId>1b837a60-3660-40f5-a368-ad856dd92ff7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topnav']/div/div/a[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e3a3c9b5-65eb-4826-b0dc-29f4955d2979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-bar-item w3-button ga-nav</value>
      <webElementGuid>327bcf1c-d556-49b3-8caf-18afe8c858b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/python/default.asp</value>
      <webElementGuid>d3d6765f-3839-4558-9f9b-a9186b0893b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Python Tutorial</value>
      <webElementGuid>e146ee8a-0acb-418c-bfb5-85d37839eb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PYTHON</value>
      <webElementGuid>ba2b1cc2-5980-45a4-a878-f148d1b62f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topnav&quot;)/div[1]/div[@class=&quot;w3-bar w3-left topnavbar&quot;]/a[@class=&quot;w3-bar-item w3-button ga-nav&quot;]</value>
      <webElementGuid>2ceceb1c-67aa-42d8-a666-4985a7d3cf59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topnav']/div/div/a[7]</value>
      <webElementGuid>02b1c75a-ca75-41a2-9dee-10e42999d20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PYTHON')]</value>
      <webElementGuid>452a1cbf-617d-46ce-ae20-fbdf2ab2c7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQL'])[3]/following::a[1]</value>
      <webElementGuid>57e5ac1d-ee72-419b-96d5-001ea721ef6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAVASCRIPT'])[1]/following::a[2]</value>
      <webElementGuid>ac70023f-638c-404e-a0dd-2aff8b6ea334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAVA'])[1]/preceding::a[1]</value>
      <webElementGuid>a204ef4e-6a4b-44fb-8dd6-69397d1e5f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PHP'])[3]/preceding::a[2]</value>
      <webElementGuid>c5cf0f0f-99b4-4d6d-a176-a07b2a0af779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PYTHON']/parent::*</value>
      <webElementGuid>33368fc6-22eb-4cf3-9bd7-ca1cb78ddb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/python/default.asp')])[3]</value>
      <webElementGuid>387c2111-740d-4a98-b18d-1a9398295a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a[7]</value>
      <webElementGuid>02a498a0-5f05-4d33-9ee3-9cb0c03a47e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/python/default.asp' and @title = 'Python Tutorial' and (text() = 'PYTHON' or . = 'PYTHON')]</value>
      <webElementGuid>de20c147-2b7d-4b0b-98cf-291c7f94b92b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
