<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Checkboxes</name>
   <tag></tag>
   <elementGuidId>d99c447d-4bac-4359-9669-ae50f435441b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recent4 > ul > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='recent4']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1e9fc9ac-9e89-40e9-bc08-88e249aa84e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/checkboxes.php</value>
      <webElementGuid>f84dae87-9cd2-49dc-b01a-d5d2b47a1d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Checkboxes</value>
      <webElementGuid>571706e5-5547-4854-b6b7-446e59b09435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recent4&quot;)/ul[1]/li[2]/a[1]</value>
      <webElementGuid>3f57a867-5423-43e7-9d7f-3b17f8d68308</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recent4']/ul/li[2]/a</value>
      <webElementGuid>24393c90-8230-4ff2-aa63-5a1aee6e30b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Checkboxes')]</value>
      <webElementGuid>1af2333c-1fdd-43cf-b0c9-1cc1292cced4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Links'])[1]/following::a[1]</value>
      <webElementGuid>2855b7f0-c4e2-4803-afc0-d0f53b7b4bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Level 1'])[1]/following::a[2]</value>
      <webElementGuid>56bfbf95-470b-46d0-b425-ab2d8ce8b3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Radio buttons'])[1]/preceding::a[1]</value>
      <webElementGuid>e7551ffe-78da-4720-bbb6-360b69700bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tables'])[1]/preceding::a[2]</value>
      <webElementGuid>7de1bad2-0397-4fbe-88e0-9dd9556ab430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Checkboxes']/parent::*</value>
      <webElementGuid>6a4b175c-4139-4702-b8eb-9066f846ef40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/checkboxes.php')]</value>
      <webElementGuid>10d57e98-daca-413d-8be5-ca1ee3fc7ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>9b5c025e-8992-4123-801a-6c66f577ab65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/checkboxes.php' and (text() = 'Checkboxes' or . = 'Checkboxes')]</value>
      <webElementGuid>7fa977ad-7ff9-4b48-828b-bb999bd63eb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
